### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by aneopsy** [ironaddicteddog/anchor-escrow#1]
Hello i'm new to anchor, and I would like to understand something.

The **Vault** account _key_ & _authority_ **seeds** are constant, so only 1 account can be create for this program ?
I'm trying to create multiple vault from the same **Initializer** and for the same **Token**, so the way to do it would be to pass an UUID as seed ?

Thank you

**Comment by ironaddicteddog** [comment]
Hi, 

> The Vault account key & authority seeds are constant, so only 1 account can be create for this program ?

In this example, the answer is yes. 

> so the way to do it would be to pass an UUID as seed ?

Yes, just make sure to store the UUID at client side for recovering the same PDA

**Comment by aneopsy** [comment]
Hey, thank you for your respond, I got it!

**Comment by 0xSeaj** [comment]
> Hi,
> 
> > The Vault account key & authority seeds are constant, so only 1 account can be create for this program ?
> 
> In this example, the answer is yes.
> 
> > so the way to do it would be to pass an UUID as seed ?
> 
> Yes, just make sure to store the UUID at client side for recovering the same PDA

Can you use the initializers public key as part of the seed in order to avoid having to store a UUID client side? Say you have an escrow that may not have a taker for n amount of days. At some point the initializer may want to cancel. During this time it's possible to lose the UUID being stored client side. Using the public key would guarantee you can always retrieve related escrow accounts for the initializer. Not sure if this would present security risks though since anyone could pass in a public key

**Comment by ironaddicteddog** [comment]
Good idea!I suppose you can verify that the public key used as PDA seed is the public of the signer.

**Comment by AUTr3ch** [comment]
Hey, I tried to derive the PDA with a UUID and the Public Key of the signer and it doesn't work. Following Error: Cross-program invocation with unauthorized signer or writable account.

If I only use the Publik Key of the signer it works fine. 

Did it work out for you to derive multiple addresses?
